# Generated by Django 4.1.1 on 2022-10-25 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='product_favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
