# Generated by Django 3.2 on 2022-09-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(default='bruzgus', max_length=50),
            preserve_default=False,
        ),
    ]
