# Generated by Django 4.1.1 on 2022-10-17 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_positivereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positivereview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positive_reviews', to='products.product'),
        ),
    ]
