# Generated by Django 4.1.1 on 2022-10-21 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_alter_positivereview_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positivereview',
            name='email',
        ),
        migrations.AlterField(
            model_name='positivereview',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
