# Generated by Django 4.1.1 on 2022-10-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_positivereview_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positivereview',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
