# Generated by Django 4.1.1 on 2022-10-23 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_positivereview_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positivereview',
            old_name='body',
            new_name='review',
        ),
    ]
