# Generated by Django 4.1.1 on 2022-10-25 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0011_rename_review_positivereview_positive_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='product_favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
